#HoneyComb
honeycomb.beeline.enabled=true
honeycomb.beeline.service-name=rbp-booking
honeycomb.beeline.dataset=rbp-booking-dataset
honeycomb.beeline.write-key=notset

springdoc.swagger-ui.config-url=/api/booking/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/api/booking/v3/api-docs
